import type { IDrawCanvasInfo } from '../types/IType';

export const startStepInfo: IDrawCanvasInfo = {
  imgId: '',
  gripper: 'body',
  mode: 'crop',
  moveX: 0,
  moveY: 0,
  cropBoxWidth: 0,
  cropBoxHeight: 0,
  fenceMaxWidth: 0,
  fenceMaxHeight: 0,
  fenceMinWidth: 0,
  fenceMinHeight: 0,
  cropRatio: null,
  cropRationLabel: 'none',
  cdProportions: 1,
  currentDomWidth: 0,
  currentDomHeight: 0,
  xCropOffset: 0,
  yCropOffset: 0,
  xDomOffset: 0,
  yDomOffset: 0,
  rawImgWidth: 0,
  rawImgHeight: 0,
  rawDomWidth: 0,
  rawDomHeight: 0,
  domWidth: 0,
  domHeight: 0,
  dWidth: 0,
  dHeight: 0,
  sWidth: 0,
  sHeight: 0,
  dx: 0,
  dy: 0,
  sx: 0,
  sy: 0,
  flipX: 1,
  flipY: 1
}